<a href="https://colab.research.google.com/github/rayssasnt/Titanic-Machine-Learning/blob/main/Titanic_Machine_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
url = 'https://raw.githubusercontent.com/rayssasnt/Titanic-Machine-Learning/refs/heads/main/titanic/train.csv'
train = pd.read_csv(url, sep=',')
train.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [3]:
url = 'https://raw.githubusercontent.com/rayssasnt/Titanic-Machine-Learning/refs/heads/main/titanic/test.csv'
test = pd.read_csv(url, sep=',')
test.head(3)

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q

# Análise de Dados

In [4]:
!pip install ydata-profiling
# usando data profiling para complementar a analise exploratória

Requirement already satisfied: ydata-profiling in /usr/local/lib/python3.12/dist-packages (4.18.1)
Requirement already satisfied: scipy<1.17,>=1.8 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (1.16.3)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.5 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.2.2)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (3.10.0)
Requirement already satisfied: pydantic<3,>=2 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.12.3)
Requirement already satisfied: PyYAML<6.1,>=6.0.3 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (6.0.3)
Requirement already satisfied: jinja2<3.2,>=3.1.6 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (3.1.6)
Requirement already satisfied: visions<0.8.2,>=0.7.5 in /usr/local/lib/python3.12/dist-packages (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (0.8.1)
Requirement already satisfied: numpy<2.4,>=1.22 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.0.2)
Requirement already satisfied: minify-html>=0.15.0 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (0.18.1)
Requirement already satisfied: filetype>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (1.2.0)
Requirement already satisfied: phik<0.13,>=0.12.5 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (0.12.5)
Requirement already satisfied: requests<3,>=2.32.0 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.32.4)
Requirement already satisfied: tqdm<5,>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (4.67.3)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (0.13.2)
Requirement already satisfied: multimethod<2,>=1.4 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (1.12)
Requirement already satisfied: statsmodels<1,>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (0.14.6)
Requirement already satisfied: typeguard<5,>=4 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (4.5.1)
Requirement already satisfied: imagehash==4.3.2 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (4.3.2)
Requirement already satisfied: wordcloud>=1.9.4 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (1.9.6)
Requirement already satisfied: dacite<2,>=1.9 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (1.9.2)
Requirement already satisfied: numba<0.63,>=0.60 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (0.60.0)
Requirement already satisfied: PyWavelets in /usr/local/lib/python3.12/dist-packages (from imagehash==4.3.2->ydata-profiling) (1.9.0)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from imagehash==4.3.2->ydata-profiling) (11.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2<3.2,>=3.1.6->ydata-profiling) (3.0.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (4.62.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (26.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba<0.63,>=0.60->ydata-profiling) (0.43.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2025.3)
Requirement already satisfied: joblib>=0.14.1 in /usr/local/lib/python3.12/dist-packages (from phik<0.13,>=0.12.5->ydata-profiling) (1.5.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (3.4.5)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (2026.2.25)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from statsmodels<1,>=0.13.2->ydata-profiling) (1.0.2)
Requirement already satisfied: attrs>=19.3.0 in /usr/local/lib/python3.12/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (25.4.0)
Requirement already satisfied: networkx>=2.4 in /usr/local/lib/python3.12/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (3.6.1)
Requirement already satisfied: puremagic in /usr/local/lib/python3.12/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (2.1.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling) (1.17.0)

In [5]:
from ydata_profiling import ProfileReport

profile = ProfileReport(train, title="titanic")

In [6]:
# profile.to_file('titanic.html')

In [7]:
train.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [8]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [9]:
train.dtypes.value_counts()

int64      5
object     5
float64    2
Name: count, dtype: int64

In [10]:
train.isnull().sum().sort_values(ascending=False)

Cabin          687
Age            177
Embarked         2
PassengerId      0
Name             0
Pclass           0
Survived         0
Sex              0
Parch            0
SibSp            0
Fare             0
Ticket           0
dtype: int64

# Analisando teste

In [11]:
test.dtypes.value_counts()

object     5
int64      4
float64    2
Name: count, dtype: int64

In [12]:
test.isnull().sum().sort_values(ascending=False)

Cabin          327
Age             86
Fare             1
Name             0
Pclass           0
PassengerId      0
Sex              0
Parch            0
SibSp            0
Ticket           0
Embarked         0
dtype: int64

Nas bases de dados existem valores nulos


Na base de **treino e teste (train e teste)** , valores como cabine, ticket e  nome serão excluidos, por alta cardinalidade

In [13]:
train = train.drop(['Name','Cabin','Ticket'], axis=1)

In [14]:
test = test.drop(['Name','Cabin','Ticket'], axis=1)

substituindo valores vazios em **idade** pela media de idade

In [15]:
train.loc[train.Age.isnull(),'Age'] = train.Age.mean()

In [16]:
test.loc[test.Age.isnull(), "Age"] = test.Age.mean()

Substituindo valores vazios em **Embarked** pela moda , "S"

In [17]:
train.Embarked.mode()

0    S
Name: Embarked, dtype: object

In [18]:
train['Embarked'].loc[train.Embarked.isnull()]

61     NaN
829    NaN
Name: Embarked, dtype: object

In [19]:
train.loc[train.Embarked.isnull(),'Embarked'] = train.Embarked.mode()[0]

In [20]:
train.query("PassengerId == 62")

    PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch  Fare Embarked
61           62         1       1  female  38.0      0      0  80.0        S

In [21]:
# valor vazio em Fare (teste)
test.loc[test.Fare.isnull(),'Fare']

152   NaN
Name: Fare, dtype: float64

In [22]:
test.loc[test.Fare.isnull(),"Fare"] = test.Fare.mean()

Conferindo valores vazios novamente

In [23]:
train.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Fare           0
Embarked       0
dtype: int64

In [24]:
test.isnull().sum()

PassengerId    0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Fare           0
Embarked       0
dtype: int64

In [25]:
train['Age'] = train['Age'].round()

transformando variaveis categoricas em numericas

In [26]:
train = train.replace("female", 1).replace("male",0)

/tmp/ipykernel_10814/2959014667.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  train = train.replace("female", 1).replace("male",0)

In [27]:
test = test.replace("female", 1).replace("male",0)

/tmp/ipykernel_10814/1803007011.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  test = test.replace("female", 1).replace("male",0)

In [28]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Sex          891 non-null    int64
 4   Age          891 non-null    float64
 5   SibSp        891 non-null    int64
 6   Parch        891 non-null    int64
 7   Fare         891 non-null    float64
 8   Embarked     891 non-null    object
dtypes: float64(2), int64(6), object(1)
memory usage: 62.8+ KB

In [29]:
train["Sex"] = train["Sex"].astype('int64')
test["Sex"] = test["Sex"].astype('int64')

# Separando XY treino e XY teste

Separando os dados e apagando o ID pois não é relevante para o modelo , mas será necessário no envio na plataforma kaggle

o DF : **train** não será alterado

vamos ultilizar o df : **treino**

In [30]:
treino = train.copy()

In [31]:
treino

     PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch     Fare Embarked
0              1         0       3    0  22.0      1      0   7.2500        S
1              2         1       1    1  38.0      1      0  71.2833        C
2              3         1       3    1  26.0      0      0   7.9250        S
3              4         1       1    1  35.0      1      0  53.1000        S
4              5         0       3    0  35.0      0      0   8.0500        S
..           ...       ...     ...  ...   ...    ...    ...      ...      ...
886          887         0       2    0  27.0      0      0  13.0000        S
887          888         1       1    1  19.0      0      0  30.0000        S
888          889         0       3    1  30.0      1      2  23.4500        S
889          890         1       1    0  26.0      0      0  30.0000        C
890          891         0       3    0  32.0      0      0   7.7500        Q

[891 rows x 9 columns]



---



---

In [32]:
teste = test.copy()

In [33]:
teste.head(2)

   PassengerId  Pclass  Sex   Age  SibSp  Parch    Fare Embarked
0          892       3    0  34.5      0      0  7.8292        Q
1          893       3    1  47.0      1      0  7.0000        S

# Encoding

In [34]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(handle_unknown='ignore', dtype='int32')

encoder = encoder.fit(treino[['Embarked']])

In [35]:
encoder.transform(treino[['Embarked']]).toarray()

array([[0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       ...,
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0]], dtype=int32)

In [36]:
encoder_df = pd.DataFrame(encoder.transform(treino[['Embarked']]).toarray(),
              columns = encoder.get_feature_names_out())

In [80]:
encoder_df.head(3)

   Embarked_C  Embarked_Q  Embarked_S
0           0           1           0
1           0           0           1
2           0           1           0

In [38]:
treino = pd.concat([treino, encoder_df],axis=1)

In [79]:
treino.head(3)

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_C,Embarked_Q,Embarked_S
0,1,0,3,0,22.0,1,0,7.2500,0,0,1
1,2,1,1,1,38.0,1,0,71.2833,1,0,0
2,3,1,3,1,26.0,0,0,7.9250,0,0,1

In [40]:
encoder_df = pd.DataFrame(encoder.transform(teste[['Embarked']]).toarray(),
              columns = encoder.get_feature_names_out())

In [41]:
teste = pd.concat([teste, encoder_df],axis=1)

In [42]:
treino = treino.drop(['Embarked'],axis=1)
teste = teste.drop(['Embarked'],axis=1)

In [43]:
teste.head(2)

,PassengerId,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_C,Embarked_Q,Embarked_S
0,892,3,0,34.5,0,0,7.8292,0,1,0
1,893,3,1,47.0,1,0,7.0000,0,0,1

In [44]:
treino.head(2)

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_C,Embarked_Q,Embarked_S
0,1,0,3,0,22.0,1,0,7.2500,0,0,1
1,2,1,1,1,38.0,1,0,71.2833,1,0,0

In [45]:
from sklearn.model_selection import train_test_split

In [46]:
X = treino.drop(['PassengerId','Survived'], axis=1)
y = treino['Survived']

In [47]:
X.head(2)

,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_C,Embarked_Q,Embarked_S
0,3,0,22.0,1,0,7.2500,0,0,1
1,1,1,38.0,1,0,71.2833,1,0,0

In [48]:
y.head(2)

0    0
1    1
Name: Survived, dtype: int64

In [49]:
X_treino , X_teste , y_treino , y_teste = train_test_split(X,y , test_size=0.3, random_state=46)

# Dummy : Modelo base

In [50]:
print(f"Treinaremos com {len(X_treino)} dados")
print(f"Testaremos com {len(X_teste)} dados")

Treinaremos com 623 dados
Testaremos com 268 dados

In [51]:
from sklearn.dummy import DummyClassifier

In [52]:
dummy = DummyClassifier(strategy='stratified') # inicia o modelo , sem o parametro 'stratified',
# o modelo sempre vai prever a classe mais comum do dataset


dummy.fit(X_treino,y_treino) # faz o ajuste

DummyClassifier(strategy='stratified')

In [53]:
y_pred = dummy.predict(X_teste) # faz a previsão
acuracia = dummy.score(y_teste,y_pred)*100 # acuracia
print(f"Acuracia: {acuracia:.2f}%")

Acuracia: 47.01%

In [54]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_teste, y_pred)

array([[96, 64],
       [68, 40]])

In [55]:
from sklearn.metrics import classification_report

print(classification_report(y_teste, y_pred))

              precision    recall  f1-score   support

           0       0.59      0.60      0.59       160
           1       0.38      0.37      0.38       108

    accuracy                           0.51       268
   macro avg       0.48      0.49      0.48       268
weighted avg       0.50      0.51      0.51       268

# Algoritmo KNN.

In [56]:
from sklearn.neighbors import KNeighborsClassifier

In [57]:
knn = KNeighborsClassifier()

In [58]:
knn.fit(X_treino, y_treino)

KNeighborsClassifier()

In [59]:
acuracia_2 = knn.score(X_teste,y_teste)*100
print(f"A acurácia foi de {acuracia_2:.2f}%")

A acurácia foi de 72.01%

# DecisionTreeClassifier

In [60]:
teste

,PassengerId,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_C,Embarked_Q,Embarked_S
0,892,3,0,34.50000,0,0,7.8292,0,1,0
1,893,3,1,47.00000,1,0,7.0000,0,0,1
2,894,2,0,62.00000,0,0,9.6875,0,1,0
3,895,3,0,27.00000,0,0,8.6625,0,0,1
4,896,3,1,22.00000,1,1,12.2875,0,0,1
...,...,...,...,...,...,...,...,...,...,...
413,1305,3,0,30.27259,0,0,8.0500,0,0,1
414,1306,1,1,39.00000,0,0,108.9000,1,0,0
415,1307,3,0,38.50000,0,0,7.2500,0,0,1
416,1308,3,0,30.27259,0,0,8.0500,0,0,1
417,1309,3,0,30.27259,1,1,22.3583,1,0,0

In [61]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

classificador_tree = DecisionTreeClassifier(max_depth=3)
classificador_tree.fit(X_treino, y_treino)
previsoes = classificador_tree.predict(X_teste)

acuracia_3 = accuracy_score(y_teste, previsoes) * 100
print(f"A acurácia do modelo foi de {acuracia_3:.2f}%")

A acurácia do modelo foi de 83.58%

# LinearSVC

In [62]:
from sklearn.svm import LinearSVC

modelo_svc = LinearSVC()
modelo_svc.fit(X_treino, y_treino)
previsoes = modelo_svc.predict(X_teste)

acuracia_4 = accuracy_score(y_teste, previsoes) * 100
print(f"A acurácia foi de {acuracia_4:.2f}%")

A acurácia foi de 82.46%

# Logistic Regression

Padronizando os dados para a regressão logística

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_treino)
X_test_scaled = scaler.transform(X_teste)

In [72]:
from sklearn.linear_model import LogisticRegression

modelo_lr = LogisticRegression()

modelo_lr.fit(X_train_scaled,y_treino)
y_pred = modelo_lr.predict(X_test_scaled)

acuracia_5 = accuracy_score(y_teste, y_pred) * 100
print(f"A acurácia foi de {acuracia_5:.2f}%")

A acurácia foi de 82.46%

# Predição

Fazendo a predição dos dados para enviar ao kaggle

In [73]:
X_teste = teste.drop("PassengerId",axis=1)

In [74]:
y_pred = classificador_tree.predict(X_teste)

In [75]:
teste['Survived'] = y_pred

In [76]:
teste[['PassengerId','Survived']]

     PassengerId  Survived
0            892         0
1            893         1
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [77]:
previssao_final = teste[['PassengerId','Survived']]
previssao_final.to_csv("Resultado_final.csv",index=False)

Salvando o Modelo

In [78]:
import pickle

with open('modelo_arvore.pkl', 'wb') as arquivo:
    pickle.dump(classificador_tree, arquivo)